apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: demo-k8s-deployment
spec:
  replicas: 3
  template:
    metadata:
      labels:
        app: hello-world
    spec:
      containers:
        - name: demo-k8s
          image: rafaelfmezquita/demo-k8s
          ports:
          - name: nodejs-port
            containerPort: 3000