apiVersion: v1
kind: Pod
metadata:
 name: demo-k8s-pod
 labels:
  app: hello-world
spec:
 containers:
 - name: demo-k8s
   image: rafaelfmezquita/demo-k8s
   ports:
   - name: nodejs-port
     containerPort: 3000